// Generated by https://quicktype.io

export interface Foreflight_Flight_Entry {
	Date: string;
	AircraftID: string;
	From: string;
	To: string;
	Route?: string;
	TimeOut: string;
	TimeOff?: string;
	TimeOn?: string;
	TimeIn: string;
	OnDuty?: string;
	OffDuty?: string;
	TotalTime: number;
	PIC?: number;
	SIC?: number;
	Night?: number;
	Solo?: number;
	CrossCountry?: number;
	NVG?: number;
	NVGOps?: number;
	Distance: number;
	DayTakeoffs: number;
	DayLandingsFullStop: number;
	NightTakeoffs: number;
	NightLandingsFullStop: number;
	AllLandings?: number;
	ActualInstrument?: number;
	SimulatedInstrument?: number;
	HobbesStart?: number;
	HobbesEnd?: number;
	TachStart?: number;
	TachEnd?: number;
	Holds?: number;
	Approach1?: string;
	Approach2?: string;
	Approach3?: string;
	Approach4?: string;
	Approach5?: string;
	Approach6?: string;
	DualGiven?: number;
	DualReceived?: number;
	SimulatedFlight?: number;
	GroundTraining?: number;
	InstructorName?: string;
	InstructorComments?: string;
	FlightReview?: boolean;
	Checkride?: boolean;
	IPC?: boolean;
	NVGProficiency?: boolean;
}

// export interface LogbookUser {
// 	[index: number]: number | string | undefined | symbol;
// 	companyName?: string;
// 	displayName?: string;
// 	uid: string;
// 	email: string;
// 	photoURL?: string;
// 	userData?: {
// 		displayName: string;
// 		nickname: string;
// 		email: string;
// 		phoneNumber: string;
// 		photoURL: string;
// 		providerId: string;
// 		uid: string;
// 		sub: string;
// 		email_verified: boolean;
// 	};
// 	aircraft?: Aircraft;
// 	subscribed?: boolean;
// 	subscription_id?: string;
// 	customer_id?: string;
// 	invoice_id?: string;
// 	checkout_session_id?: string;
// 	auth?: User;
// 	user_metadata?: { subcribed: boolean };
// 	logbookEntries?: FlightEntry[];
// 	originalFilenames?: string[];
// }
// Generated by https://quicktype.io

// export interface FlightEntry {
// 	_id: string;
// 	Distance: number;
// 	AircraftID: string;
// 	Date: string;
// 	TimeOut: string;
// 	TimeIn: string;
// 	From: string;
// 	To: string;
// 	Route: string;
// 	TotalTime: number;
// 	DayTakeoffs: number;
// 	DayLandingsFullStop: number;
// 	NightTakeoffs: number;
// 	NightLandingsFullStop: number;
// 	PIC?: number;
// 	Solo?: number;
// 	CrossCountry?: number;

// 	positionData: Position[];
// 	originalFilename: string;
// }

// export interface Position {
// 	positionName: string;
// 	positionInfo: PositionInfo;
// }

// export interface PositionInfo {
// 	lcltime: string;
// 	lcldate: string;
// 	utcofst: object;
// 	latitude: number;
// 	longitude: number;
// 	ias: number;
// 	e1ng?: number;
// 	atvwpt: string;
// 	wptdst: number;
// 	altind: number;
// 	altmsl: number;
// 	tas: number;
// 	vspd: number;
// }

// export interface Aircraft {
// 	AircraftId: string;
// 	EquipmentType: string;
// 	TypeCode: string;
// 	Make: string;
// 	Model: string;
// 	Category: string;
// 	Class: string;
// 	GearType: string;
// 	EngineType: string;
// 	Complex: boolean;
// 	TAA: boolean;
// 	HighPerformance: boolean;
// 	Pressurized: boolean;
// }

// export interface PapaReturn {
// 	data: PapaReturnData;
// 	errors: object;
// 	meta: object;
// }

// export interface PapaReturnData {
// 	[index: string]: string;
// }

// export interface AptObj {
// 	[index: string]: string | number;
// 	date: string;
// 	apt: string;
// 	tz: string;
// 	nTime: string;
// }

// export interface PositionData {
//   tOut?: DefaultFlightParams;
//   tOff?: DefaultFlightParams;
//   tOn?: DefaultFlightParams;
//   tIn?: DefaultFlightParams;
//   wpts?: DefaultFlightParams[];
//   routeString?: string;
// }
